import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/layoutDesign/Header";
import { connectdb } from "@/config/db";

import StoreProvider from "./StoreProvider";
import SessionProviderContext from "./SessionProviderContext";
import CartLayout from "@/components/CartLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GlobeMart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
 
}) {
  const conn = await connectdb();

  return (
    <html lang="en">
      <body className={inter.className}>
       
          <StoreProvider>
             <SessionProviderContext>
            <Header />

            <div className="flex mx-4 mt-[8rem] md:mt-[6rem] lg:mt-[6rem] ">
              {children}
            </div>
            <CartLayout/>
            </SessionProviderContext>
          </StoreProvider>
        
      </body>
    </html>
  );
}
